name: Generate Contribution Snake Animation

on:
  schedule:
    # Run automatically every 24 hours at midnight UTC
    - cron: "0 0 * * *"
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generates a snake game from a github user contributions graph, output a svg animation
      - name: Generate Contribution Grid Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sanmitpatil07
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # Push the generated SVGs to the output branch
      - name: Push Snake SVGs to Output Branch
        uses: CrazyMax/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
